language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
before_install:
   - "cpanm Test::More"
   - "cpanm Storable"
   - "sudo apt-get install -y libzmq3-dev"
   - "cpanm ZMQ::LibZMQ3"
   - "cpanm Devel::Cover::Report::Coveralls"
   - "export RELEASE_TESTING=1"
   - "perl Makefile.PL"
script:
   - make test
   - cover -test -report coveralls
